---

- hosts: localhost
  connection: local
  pre_tasks:
    - name: pre-validate sudo password
      become: yes
      changed_when: false
      check_mode: yes
      shell:
        cmd: "true"
  roles:
    - install-homebrew
    # - user-interface
    # - geerlingguy.homebrew

