---

- name: Set keyboard InitialKeyRepeat
  osx_defaults:
    domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: float
    value: "{{osx_defaults.InitialKeyRepeat}}"
    state: present

- name: Set keyboard KeyRepeat
  osx_defaults:
    domain: NSGlobalDomain
    key: KeyRepeat
    type: float
    value: "{{osx_defaults.KeyRepeat}}"
    state: present

- name: Set trackpad scroll direction
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    type: bool
    value: "NO"
    state: present

